name: CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: voicebot-app
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}